### ISSUE TITLE
Noetic-devel release

### ISSUE THREAD

**Issue by martihmy** [justagist/panda_simulator#13]
Are you planning to make a noetic-devel version?

**Comment by justagist** [comment]
Hi, I don't have immediate plans for doing it, but hopefully it should not be too difficult to port to noetic and should be a matter of updating the dependencies to the corresponding noetic versions.
I would be glad to review and accept a PR if you manage to make changes for noetic support.

**Comment by justagist** [comment]
Hi Martin,
I received your mail, but the return mail you provided does not seem valid.
Best,
Saif
