### ISSUE TITLE
Issue with set of controllers in Kinetic

### ISSUE THREAD

**Issue by rpl-as-ucl** [justagist/panda_simulator#14]
Hi, we try to use the MoveIt demo, on Kinetic, but we get an error:

[ERROR] [1604587753.964362125, 179.575000000]: Unable to identify any set of controllers that can actuate the specified joints: [ panda_joint1 panda_joint2 panda_joint3 panda_joint4 panda_joint5 panda_joint6 panda_joint7 ]
[ERROR] [1604587753.964425957, 179.575000000]: Known controllers and their joints:

[ERROR] [1604587753.964546268, 179.575000000]: Apparently trajectory initialization failed

**Comment by justagist** [comment]
Please make sure you have moveit packages installed (`apt-get install ros-kinetic-moveit`)
