### ISSUE TITLE
Does this project have position control in Cartesian space?

### ISSUE THREAD

**Issue by HIT-Ajian** [justagist/panda_simulator#17]
Moveit motion planning will automatically detect collisions, but this is not what I want, so I don't want to use ROS motion planning. Does this project support motion planning in Cartesian space? I don't find a related package or library about Cartesian space.

**Comment by justagist** [comment]
> Does this project support motion planning in Cartesian space? I don't find a related package or library about Cartesian space.

I am not sure what you mean when you say 'motion planning in cartesian space'. This package does not provide any planners at all. 

> Title: Does this project have position control in Cartesian space?

If you are looking for a controller for controlling the end-effector of the robot in cartesian space (which is the title of the issue), a direct controller is not provided, but you can write your own task-space controller using the provided joint-space controllers. As an example, see the task-space control demos provided. ([1](https://github.com/justagist/panda_simulator/blob/melodic-devel/panda_simulator_examples/scripts/task_space_control_using_sim_only.py), [2](https://github.com/justagist/panda_simulator/blob/melodic-devel/panda_simulator_examples/scripts/task_space_control_with_fri.py))
Here's the animation of the demo. Here the robot's end-effector is controlled using a PD controller in task-space written over the joint torque controllers.
![vid](https://github.com/justagist/panda_simulator/raw/melodic-devel/assets/ts_demo.gif)
