### ISSUE TITLE
Minjerk python 3

### ISSUE THREAD

**Issue by NoeMurr** [justagist/panda_simulator#23]
I'm trying to run the simulator in ros noetic on ubuntu.

I compiled correctly the simulator. I needed to hand compile even the [franka-ros](https://github.com/frankaemika/franka_ros) package because the package is not available in noetic.

The biggest problem in compiling is that `rosdep` is not working so you have to run the command `rosdep instal --rosdistro noetic [...]` and for each package that it is saying to be missing you have to add it with `apt install [...]`.

After that I tried to run the simulator with `roslaunch panda_gazebo panda_world.launch`  but the scripts `joint_trajectory_action_server.py` and `gripper_action_server` where looking for the command python that was not present on my system so i changed it with python3. 

Even after adding python3 I had some problems with the dependencies, the one listed in `requirements.txt`are not sufficient. 
Now python cannot find the package `minjerk` that is widely use inside the scripts. I can't find it on PyPI I think it is refering to [this one](joint_trajectory_action_server.py). Is it that? if yes how do you advice to install it?

**Comment by justagist** [comment]
Hi, at the moment there is no support for ros noetic or python 3, and there are no immediate plans for development. 
I haven't tried setting it up on noetic/python3 yet, so I can't really give you any advice in this area, sorry about that. (see #13 -- I know they were also trying to create a noetic version, they may be able to help you).
