### ISSUE TITLE
Incompatible with latest version of numpy-quaternion

### ISSUE THREAD

**Issue by Pencilvesterr** [justagist/panda_simulator#30]
The setup bash script installs the latest version of quaternion (currently 2021.3.11.10.32.22). The resulting error occurs when trying to start one of the demo scripts. I resolved the error for myself by using a version numpy-quaternion==2018.10.1.15.39.8. 

![image](https://user-images.githubusercontent.com/45610105/110888706-d0d99c80-8340-11eb-8ea5-fe09ab8e9137.png)

**Comment by justagist** [comment]
Looks like there's a bug in the new release of numpy-quaternion. As you suggested, I've specified version in the requirements file to avoid it for now.
Thanks for pointing this out!
