### ISSUE TITLE
Invoking "cmake" failed

### ISSUE THREAD

**Issue by Sission** [justagist/panda_simulator#33]
HI! I am following your instructions to catkin_make panda_simulator
I used franka_ros 0.6.0; panda_simulator kinetic-devel, libranka 0.7.0
When I catkin_make:

-- ~~  traversing 17 packages in topological order:
-- ~~  - franka_panda_description
-- ~~  - franka_ros_interface (metapackage)
-- ~~  - orocos_kdl (plain cmake)
-- ~~  - orocos_kinematics_dynamics
-- ~~  - panda_simulator (metapackage)
-- ~~  - python_orocos_kdl (plain cmake)
-- ~~  - panda_hardware_interface
-- ~~  - franka_core_msgs
-- ~~  - panda_sim_controllers
-- ~~  - franka_interface
-- ~~  - franka_ros_controllers
-- ~~  - franka_moveit
-- ~~  - franka_tools
-- ~~  - panda_sim_custom_action_server
-- ~~  - panda_gazebo
-- ~~  - panda_sim_moveit
-- ~~  - panda_simulator_examples
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:95 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:67 (catkin_workspace)

Thanks!

**Comment by justagist** [comment]
Please use `catkin build` for building your workspace as explained in the instructions. If you want to use `catkin_make`, you can try `catkin_make_isolated` instead as the error message clearly states, but for this all dependencies must be built correctly.
