### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by Sission** [justagist/panda_simulator#34]
Hello! I suffered this error when I catkin build. Could you help me with this? Thanks!

Errors     << franka_interface:make /home/airlab/catkin_ws/logs/franka_interface/build.make.002.log
/home/airlab/catkin_ws/src/franka_ros_interface/franka_interface/src/robot_state_controller.cpp: In member function ‘void franka_interface::CustomFrankaStateController::publishFrankaState(const ros::Time&)’:
/home/airlab/catkin_ws/src/franka_ros_interface/franka_interface/src/robot_state_controller.cpp:361:39: error: ‘struct franka::RobotState’ has no member named ‘NE_T_EE’; did you mean ‘O_T_EE’?
     static_assert(sizeof(robot_state_.NE_T_EE) == sizeof(robot_state_.O_T_EE),
                                       ^~~~~~~
                                       O_T_EE
/home/airlab/catkin_ws/src/franka_ros_interface/franka_interface/src/robot_state_controller.cpp:369:63: error: ‘struct franka::RobotState’ has no member named ‘F_T_NE’; did you mean ‘F_T_EE’?
         publisher_franka_state_.msg_.F_T_NE[i] = robot_state_.F_T_NE[i];
                                                               ^~~~~~
                                                               F_T_EE
/home/airlab/catkin_ws/src/franka_ros_interface/franka_interface/src/robot_state_controller.cpp:370:64: error: ‘struct franka::RobotState’ has no member named ‘NE_T_EE’; did you mean ‘O_T_EE’?
         publisher_franka_state_.msg_.NE_T_EE[i] = robot_state_.NE_T_EE[i];
                                                                ^~~~~~~
                                                                O_T_EE
/home/airlab/catkin_ws/src/franka_ros_interface/franka_interface/src/robot_state_controller.cpp: In member function ‘void franka_interface::CustomFrankaStateController::publishTransforms(const ros::Time&)’:
/home/airlab/catkin_ws/src/franka_ros_interface/franka_interface/src/robot_state_controller.cpp:474:74: error: ‘struct franka::RobotState’ has no member named ‘F_T_NE’; did you mean ‘F_T_EE’?
     tf::StampedTransform stamped_transform(convertArrayToTf(robot_state_.F_T_NE), time,
                                                                          ^~~~~~
                                                                          F_T_EE
/home/airlab/catkin_ws/src/franka_ros_interface/franka_interface/src/robot_state_controller.cpp:480:76: error: ‘struct franka::RobotState’ has no member named ‘NE_T_EE’; did you mean ‘O_T_EE’?
     stamped_transform = tf::StampedTransform(convertArrayToTf(robot_state_.NE_T_EE), time,
                                                                            ^~~~~~~
                                                                            O_T_EE

**Comment by justagist** [comment]
The missing variables are defined in v0.7.1 of `franka-ros`. Make sure you have installed >0.7.1 of `franka-ros`.
If you are trying to build it for older version, you have to use an older commit of this repository (see the instructions in the README of this repo).
