### ISSUE TITLE
Dual-arm Simulation using PandaRobotHWSim

### ISSUE THREAD

**Issue by D-Blade** [justagist/panda_simulator#41]
Hello, thank you very much for your work!

I'm trying to set up a dual-arm simulation environment using the PandaRobotHWSim interface but cannot find a convenient way to configure different namespaces for the controllers and the topics. According to the source code of the plugin, it seems that the namespace of the controller is somehow hard-coded and cannot be modified. Could you please provide some advice if possible? Thank you very much in advance.

**Comment by justagist** [comment]
Hi,
Glad you found this package useful.

The PandaRobotHWSim interface was not written for a multi-robot setup originally, and a lot of the code is, as you said, hard-coded for a single instance of the robot. The namespaces being used in the interface are directly loaded from the `franka_panda_description` package (see [`panda.transmission.xacro`](https://github.com/justagist/franka_panda_description/blob/90a70304deb0a66d273b39be4c6df41a0faba149/robots/panda.transmission.xacro#L19) file). However, I am not sure how the custom hardware interface would respond to having multiple instances of it running simultaneously, but feel free to test it out.
If you don't really need to use `franka_ros_interface` or `panda_robot` interfaces, and only want to have multiple instances of the arm in the simulator, then I would recommend trying to modify a simulator that uses one of the default gazebo hardware interfaces; it would be easier to make the required changes to the launch file (and maybe the description files as well) to load two robots in the simulator. One example of such a package that uses the default ROS/Gazebo interfaces is [`gazebo_panda`](https://github.com/justagist/gazebo_panda).
Sorry for not being more helpful. If you manage to get a dual-arm setup working with either of these simulator packages, it would be great if you could contribute to the repositories with a PR!
