### ISSUE TITLE
start the franka_example_controller 

### ISSUE THREAD

**Issue by phknestel** [justagist/panda_simulator#52]
this is more a question than an issue, how is it possible to launch the franka example controller from the franka fci documentation in this simulator? The example controllers are started with a robot_ip and use the franka_hw interfaces. 

Here is the link for the example controllers: https://frankaemika.github.io/docs/franka_ros.html#franka-example-controllers

**Comment by justagist** [comment]
Hi,
These examples are not directly supported in this simulator as it uses custom hardware interfaces that are different to those in `franka_ros`. This simulator is mainly intended to be used as a safe environment for testing `franka_ros_interface` codes in simulation before deploying on a real robot, by *trying* to mimic the feedback and dynamics of the physical robot.
If you want to simulate the `franka_ros` examples, you may find this useful: https://github.com/justagist/panda_simulator/issues/25#issuecomment-814293067, using a different definition of the robot interface as a plugin in a simplified gazebo simulator.
