### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by rouzinho** [justagist/panda_simulator#56]
Hi !

I run the simulator on noetic and I had trouble using some gazebo model objects I was previously using. it seems like there is no gravity in the world launched. That caused my objects to be affected and float around when I interact with them. I tried to set the gravity within the object sdf but without effect (the world seemed to override this). I activated the gravity in the panda.world and I can interact with my objects like before without (for now) bad consequences for the robot. I precise that I use the moveit interface.
Was there a specific reason to disable the gravity ?

**Comment by justagist** [comment]
Hi @rouzinho,
That is a good question. The gravity compensation in the simulator is not very good at the moment (see last point in https://github.com/justagist/panda_simulator#known-issues). This can be seen only if you use velocity or torque control, and should not be a problem if you use position control.

**Comment by rouzinho** [comment]
Okay, so I guess I'll keep going this way. Thanks !
