### ISSUE TITLE
Action client not connected: position_joint_trajectory_controller/follow_joint_trajectory

### ISSUE THREAD

**Issue by akhilsanand** [justagist/panda_simulator#57]
I am having trouble with the same issue as justagist/franka_ros_interface#24 ,
[ERROR] [1634815472.331006214, 17.186000000]: Action client not connected: position_joint_trajectory_controller/follow_joint_trajectory 

running the simulator using noetic. tried installing joint-trajectory-controller but it did not solve the issue :(

**Comment by justagist** [comment]
justagist/franka_ros_interface#24 is in regard to the physical robot and not the simulator.
Please raise issues related to the simulator in the simulator's repo next time.
Regarding the issue, are you trying to run any specific demo, or just starting the simulator? What are the steps/commands you have run?

**Comment by akhilsanand** [comment]
Hi , sorry about posting in the wrong repo.

I am just starting the simulator with loading moveit , I am running,

roslaunch panda_gazebo panda_world.launch start_moveit:=true.

here is the summary from the terminal 
[summary.docx](https://github.com/justagist/panda_simulator/files/7389369/summary.docx)

**Comment by justagist** [comment]
Please start the moveit server separately as mentioned in the readme. Starting them together sometimes causes issues with the order in which the nodes are loaded.

**Comment by akhilsanand** [comment]
thank you :) it works by starting the moveit server separately.
