### ISSUE TITLE
RvizMarkers

### ISSUE THREAD

**Issue by moritzknaust** [justagist/panda_simulator#7]
Hi!
Your simulation frameworks looks really promising and i want to try it! But I have one simple problem: What is the RvizMarker used in the examples? It is required to run the example but i cannot find it anywhere. 

Can you tell me which package I have to install?

**Comment by justagist** [comment]
Hi @moritzknaust! 
Sorry, that's my bad! The missing file should now be available (commit a45ce409973da2e362dbc864e380e953694bfe19 for melodic-devel branch). You won't need additional packages.
Thanks for pointing this out!

**Comment by moritzknaust** [comment]
Thank you for the really fast response! Now it is working fine!
